### ISSUE TITLE
Support for classicalradio,radiotunes,jazzradio,rockradio

### ISSUE THREAD

**Issue by lethak** [lethak/LTKDIFMU-userscript#5]
to be tested
```
// @include     https://*.di.fm*
// @include     https://*.classicalradio.com*
// @include     https://*.radiotunes.com*
// @include     https://*.jazzradio.com*
// @include     https://*.rockradio.com*
```

**Comment by lethak** [comment]
Alright, this has been added into master, if someone can give me some feedback if its working in the long run, it would be much appreciated !

**Comment by 0x416c69** [comment]
Tested now with Chrome 63.0.3239.84 (Official Build) (64-bit) on RadioTunes.com
Working perfectly, console: VM8917:94 [DIUserscript] webplayer:ads:requestMidrollAd rejected
https://github.com/lethak/digitally_imported_userscript/blob/master/DIU.user.js#L120
You're defining a property, will this also increase audio quality like website's premium feature?
Btw, thanks for this man, you save lives 😂

**Comment by lethak** [comment]
Hi, thanks for the feedback !
What I am doing is making the client (your browser) think you are premium, but the server knows you are not, so you can't have the features going with it ;) this is only done to fool parts of the client into thinking you don't need to be displayed ads.
